USE rd_ms_db;

CREATE TABLE IF NOT EXISTS rd_ms_db.lecture (
    lecture_id BIGINT(20) NOT NULL AUTO_INCREMENT,
    agenda VARCHAR(255) NULL DEFAULT NULL,
    description VARCHAR(255) NULL DEFAULT NULL,
    device VARCHAR(255) NULL DEFAULT NULL,
    duration BIGINT(20) NULL DEFAULT NULL,
    linkTopicEpam VARCHAR(255) NULL DEFAULT NULL,
    linkVideoPortalEpam VARCHAR(255) NULL DEFAULT NULL,
    linkYoutube VARCHAR(255) NULL DEFAULT NULL,
    name VARCHAR(255) NULL DEFAULT NULL,
    typeOfPlace VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (lecture_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS rd_ms_db.practicaltask (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    duration BIGINT(20) NULL DEFAULT NULL,
    linkToDescription VARCHAR(255) NULL DEFAULT NULL,
    name VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS rd_ms_db.topic (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    duration BIGINT(20) NULL DEFAULT NULL,
    linkToDescription VARCHAR(255) NULL DEFAULT NULL,
    name VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS rd_ms_db.module (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    duration BIGINT(20) NULL DEFAULT NULL,
    linkToDescription VARCHAR(255) NULL DEFAULT NULL,
    name VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS rd_ms_db.program (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    LinkToDescription VARCHAR(255) NULL DEFAULT NULL,
    duration BIGINT(20) NULL DEFAULT NULL,
    name VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS rd_ms_db.users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX email_UNIQUE (email)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS rd_ms_db.roles (
    id INT(11) NOT NULL AUTO_INCREMENT,
    role VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX role_UNIQUE (role)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
